# rbenvインストール
# git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
- name: install rbenv
  become: true
  git: 
    repo: https://github.com/sstephenson/rbenv.git 
    dest: /home/ec2-user/.rbenv
  become_user: ec2-user
  become_method: sudo


- name: edit permission rbenv
  become: true
  file:
    path: /home/ec2-user/.rbenv
    state: directory
    owner: ec2-user
    group: ec2-user


# パスを通す
# echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="/home/ec2-user/.rbenv/bin:$PATH"'

# ~/.bash_profileは、ユーザーのログインシェルで起動時に読み込まれるスクリプトファイル。
# 提供されたコードは、~/.bash_profileファイルにrbenvの初期化を追加することで、ログインシェル起動時に自動的にrbenvを初期化する。
# echo 'eval "$(rbenv init -)"' >> ~/.bash_profile 
- name: eval rbenv init
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'

# 環境変数や設定の変更を現在のシェルに反映させる
# source .bash_profile
- name: rbenv setting
  shell: bash -lc "source ~/.bash_profile"



# ruby-buildのインストール 
# git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  become: true



# rubyがインストールされているか確認
- name: check ruby install
  shell: bash -lc "rbenv version | grep {{ ruby_version }}"
  register: ruby_exists
  changed_when: no
  ignore_errors: true
  become: true

# インストールされていなければrubyをインストール
- name: ruby install
  shell: bash -lc "rbenv install {{ ruby_version }}"
  timeout: 1200
  when: ruby_exists is failed
  become: true

# rbenvは複数のrubyバージョンを管理できるため、システムのデフォルトのバージョンを設定
- name: check rbenv global
  shell: bash -lc "rbenv version | grep {{ ruby_version }}"
  register: rbenv_default
  changed_when: False
  ignore_errors: True
  become: true

- name: set rbenv global
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: rbenv_default is failed
  become: true

- name: rbenv rehash
  shell: bash -lc "rbenv rehash"
  when: rbenv_default is failed
  become: true