version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.4
  ansible-playbook: orbss/ansible-playbook@0.0.5
 #ruby: circleci/ruby@2.0.1

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation-template/*.yml


  execute-CloudFormation:
    executor: aws-cli/default    # 実行者
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          name: deploy Cloudformation
          command: |
            set -x
            aws cloudformation deploy --template cloudformation-template/raisetech-lecture10-vpc.yml --stack-name lecture13-VPC
            aws cloudformation deploy --template cloudformation-template/raisetech-lecture13-ec2.yml --stack-name lecture13-EC2
#aws cloudformation deploy --template cloudformation-template/raisetech-lecture10-rds.yml --stack-name lecture13-RDS
#aws cloudformation deploy --template cloudformation-template/raisetech-lecture10-alb.yml --stack-name lecture13-ALB
#aws cloudformation deploy --template cloudformation-template/raisetech-lecture10-s3.yml --stack-name lecture13-S3 
# set -x コマンドをスクリプトの先頭に追加すると、シェルが各コマンドを実行する前にそのコマンドを表示します。

  execute-Ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - b3:28:88:18:a9:81:61:40:04:54:0b:9c:2d:fe:52:b3
      - ansible-playbook/install:
          version: '2.10.7'
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-u ec2-user -i ansible/inventory --private-key ../../keypair/CFnKeyPair.pem'

#  execute-serverspec:
#    executor: ruby/default
#    steps:
#    - checkout
#    - ruby/install-deps: 
#        app-dir: serverspec
#    - run: |
#        cd serverspec
#        bundle exec rake spec  

# CircleCIはデフォルトでRubyの環境を提供しており、必要なGemパッケージをインストールすることができる。
# ruby/install-deps orbが使用されている場合、そのorbは自動的にbundle installを実行。
# ruby/install-deps orbは、指定されたディレクトリ（app-dir）内のGemfileに基づいて依存関係を解決し、必要なGemパッケージをインストール。
# 明示的にbundle installステップを追加する必要はない。ruby/install-deps orbによって自動的に行われる。

workflows:
  raisetech:
    jobs:
      - cfn-lint
      - execute-CloudFormation:      # executeCloudFormation ジョブは cfn-lint ジョブが正常に完了した後に実行
          requires:
            - cfn-lint
      - execute-Ansible:
          requires:
            - execute-CloudFormation
      #- execute-serverspec:
      #    requires:
      #      - execute-Ansible

