# mysqlのインストール
# MariaDBの削除
- name: Remove MariaDB
  become: true
  yum:
    name: mariadb-server
    state: absent

# 公開リポジトリを追加
- name: Install MySQL repository
  become: true
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm'
    state: present

# mysqlクライアントインストール
- name: install mysql-community-client.x86_64
  become: true
  yum:
    name: mysql-community-client.x86_64
    state: present

- name: Start MySQL service
  become: true
  service:
    name: mysqld
    state: started
    enabled: yes



# mysql本体をインストール
#- name: Install MySQL community server
#  become: true
#  yum:
#    name: mysql-community-server
#    state: present

