AWSTemplateFormatVersion: 2010-09-09
Description: ALB template
Resources:
#ALB作成
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: raisetech-lecture10-elb
      Scheme: internet-facing    # インターネット向け
      Type: application
      Subnets: 
      - !ImportValue raisetech-lecture10-publicSubnet1a-id
      - !ImportValue raisetech-lecture10-publicSubnet1c-id
      SecurityGroups: 
      - !ImportValue raisetech-lecture10-sg-ec2-id
      IpAddressType: ipv4
      Tags:
      - Key: Name
        Value: raisetech-lecture10-alb

#ターゲットグループ作成
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: raisetech-lecture10-targetgroup
      VpcId: !ImportValue rasetech-lecture10-vpc-id
      Protocol: HTTP
      ProtocolVersion: HTTP1
      Port: 80
      TargetType: instance
      Targets: 
      - Id: !ImportValue rasetech-lecture10-ec2-id
        Port: 80
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher: 
        HttpCode: 200
      Tags:
      - Key: Name
        Value: raisetech-lecture10-targetgroup

#リスナー設定
  ListenerResource:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions: 
      - TargetGroupArn: !Ref TargetGroup
        Type: forward                         # 指定されたターゲットグループにリクエストを転送

#Outputsセクション設定  
Outputs:
  ALBOutput:
    Value: !Ref ALB
    Export:
      Name: ALB-id