# node.jsのインストール
# 
- name: Check if EPEL repository is already installed
  command: amazon-linux-extras list | grep -q '^epel\s'
  changed_when: false
  register: epel_installed
  become: true
      
- name: Check if NVM is already installed
  command: test -d ~/.nvm
  changed_when: false
  register: nvm_installed
  become: true

- name: EPEL install
  become: true
  command: amazon-linux-extras install epel -y
  when: not epel_installed.stdout and not nvm_installed.stdout

- name: Update yum cache
  command: yum clean all && yum makecache
  become: true
  when: not epel_installed.stdout

- name: Node.jsのインストール
  become: true
  yum:
    name: nodejs
    state: present

- name: インストールしたNode.jsの確認
  become: true
  command: node --version
  register: node_version
  changed_when: false

- name: Node.jsのバージョン表示
  debug:
    var: node_version.stdout

- name: Install prerequisites
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - wget
    - gcc-c++
    - openssl-devel
    - libffi-devel

- name: Update GLIBC version (example)
  become: true
  command: yum update glibc -y
  register: glibc_update_result
  changed_when: glibc_update_result is changed
  ignore_errors: true

- name: Reboot system
  become: true
  reboot:
  when: glibc_update_result is changed

- name: Wait for system to reboot
  wait_for_connection:
    delay: 30
    timeout: 300

- name: Download and install NVM
  become: true
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    source ~/.nvm/nvm.sh
  changed_when: false

- name: Set NVM environment variables
  lineinfile:
    dest: ~/.bashrc
    line: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  changed_when: false

- name: Install Node.js using NVM
  shell: |
    source ~/.nvm/nvm.sh
    nvm install node
  changed_when: false

- name: Verify Node.js installation
  become: true
  shell: |
    source ~/.nvm/nvm.sh
    node --version
  register: node_version
  changed_when: false

- name: Change Node.js version
  shell: |
    source ~/.nvm/nvm.sh
    nvm install 17.9.1
    nvm alias default 17.9.1
  changed_when: false
