
- name: Update yum cache
  yum:
    name: "*"
    state: latest

- name: Install prerequisites
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - gcc-c++
    - glibc-headers
    - openssl-devel
    - readline
    - libyaml-devel
    - readline-devel
    - zlib
    - zlib-devel
    - libffi-devel
    - libxml2
    - libxslt
    - libxml2-devel
    - libxslt-devel
    - sqlite-devel
    - libpng-devel
    - libjpeg-devel
    - libtiff-devel
    - gcc
    - mysql-devel
    - patch
    - libicu-devel
    - ImageMagick
    - ImageMagick-devel
    - libcurl
    - libcurl-devel
    - curl

- name: Download and install Node.js
  get_url:
    url: "https://nodejs.org/dist/v17.9.1/node-v17.9.1-linux-x64.tar.gz"
    dest: "/tmp/node-v17.9.1-linux-x64.tar.gz"

- name: Extract Node.js
  unarchive:
    src: "/tmp/node-v17.9.1-linux-x64.tar.gz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/node-v17.9.1-linux-x64"

- name: Create symbolic links for Node.js
  file:
    src: "/opt/node-v17.9.1-linux-x64"
    dest: "/opt/node"
    state: link

- name: Add Node.js to PATH
  lineinfile:
    path: "/etc/profile.d/node.sh"
    line: 'export PATH="/opt/node/bin:$PATH"'
    create: yes

- name: Install Yarn
  npm:
    name: yarn
    version: 1.22.19
    state: present
    global: yes
